//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Nakasendo.Gakupetit.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Nakasendo.Gakupetit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Can&apos;t open the chosen file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BitmapEffectsMessageCantOpenFile {
            get {
                return ResourceManager.GetString("BitmapEffectsMessageCantOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid file format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BitmapEffectsMessageFileFormatError {
            get {
                return ResourceManager.GetString("BitmapEffectsMessageFileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File open error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BitmapEffectsMessageOpenFileError {
            get {
                return ResourceManager.GetString("BitmapEffectsMessageOpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gakupetit! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Gakupetit {
            get {
                return ResourceManager.GetString("Gakupetit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Cancel]                               : Abort sequential processing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainCancel {
            get {
                return ResourceManager.GetString("MainCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple files are specified. Do you want to open these files as sequential processing mode? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainConfirmMultipleFile {
            get {
                return ResourceManager.GetString("MainConfirmMultipleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm sequential processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainConfirmProcessing {
            get {
                return ResourceManager.GetString("MainConfirmProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag to get the color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainDragColor {
            get {
                return ResourceManager.GetString("MainDragColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elapsed time : {0,4}ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainElapsedTime {
            get {
                return ResourceManager.GetString("MainElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extension                             : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainExtention {
            get {
                return ResourceManager.GetString("MainExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t find {0}. Do you want to skip this file and continue sequential processing? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainFileNotFoundException {
            get {
                return ResourceManager.GetString("MainFileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frame color                         : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainFrameColor {
            get {
                return ResourceManager.GetString("MainFrameColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frame type                          : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainFrameType {
            get {
                return ResourceManager.GetString("MainFrameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify image files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainImageFileMessage {
            get {
                return ResourceManager.GetString("MainImageFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image size                           : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainImageSize {
            get {
                return ResourceManager.GetString("MainImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file will open in normal mode. If you want to open in sequential processing mode, select multiple image files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMassageMultipleFile {
            get {
                return ResourceManager.GetString("MainMassageMultipleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you want to use transparent, please save as PNG instead of JPEG, and the output file size will increase. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMessageTransparent {
            get {
                return ResourceManager.GetString("MainMessageTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [N     o]                                : Open dialog and modify settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainNo {
            get {
                return ResourceManager.GetString("MainNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now on sequential processing. Dou you want to stop the sequential processing? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainNowOnProcessing {
            get {
                return ResourceManager.GetString("MainNowOnProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source image folder             : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainOriginalImageFolder {
            get {
                return ResourceManager.GetString("MainOriginalImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to open {0}. Do you want to skip this file and continue sequential processing? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainOutOfMemoryException {
            get {
                return ResourceManager.GetString("MainOutOfMemoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prefix                                   : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainPrefix {
            get {
                return ResourceManager.GetString("MainPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy policy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainPrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("MainPrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This application accesses the photo data specified by the user to process the photo. It will not be used or held for any other purposes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainPrivacyPoricyText {
            get {
                return ResourceManager.GetString("MainPrivacyPoricyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} files were saved to &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainProcessed {
            get {
                return ResourceManager.GetString("MainProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   These files are saved with the following settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainProcImageFiles {
            get {
                return ResourceManager.GetString("MainProcImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} files are saved with the following settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainProcImageManyFiles {
            get {
                return ResourceManager.GetString("MainProcImageManyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renumber                           : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainRenumber {
            get {
                return ResourceManager.GetString("MainRenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resize type                          : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainResizeType {
            get {
                return ResourceManager.GetString("MainResizeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination image folder      : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainSaveImageFolder {
            get {
                return ResourceManager.GetString("MainSaveImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This software can&apos;t be launched multiple times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainSingletonMessage {
            get {
                return ResourceManager.GetString("MainSingletonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sequential processing mode. Please specify multiple files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainSpecifyMultipleFile {
            get {
                return ResourceManager.GetString("MainSpecifyMultipleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple files were not selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainTitleMultipleFile {
            get {
                return ResourceManager.GetString("MainTitleMultipleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value                                   : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainValue {
            get {
                return ResourceManager.GetString("MainValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Y  e  s]                                : Continue with these settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainYes {
            get {
                return ResourceManager.GetString("MainYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ex. :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveEx {
            get {
                return ResourceManager.GetString("SaveEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy default 10 images for  User defined/Green back to {0}. Is it OK? After copy the files, you can edit the copied images. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFileCopyCheckMessage {
            get {
                return ResourceManager.GetString("SaveFileCopyCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm for file copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFileCopyCheckTitle {
            get {
                return ResourceManager.GetString("SaveFileCopyCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t copy the files. User defined/Green back images may be used. Choose another effect, then do it once again. ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFileCopyErrorMessage {
            get {
                return ResourceManager.GetString("SaveFileCopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File copy error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFIleCopyErrorTitle {
            get {
                return ResourceManager.GetString("SaveFIleCopyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The letter &apos;{0}&apos; can&apos;t apply for the file name. It was replaced to &apos;_&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFileNameCheckMessage {
            get {
                return ResourceManager.GetString("SaveFileNameCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name availability check に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFileNameCheckTitle {
            get {
                return ResourceManager.GetString("SaveFileNameCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizeMode1 {
            get {
                return ResourceManager.GetString("SizeMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   from size list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizeMode2 {
            get {
                return ResourceManager.GetString("SizeMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   from width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizeMode3 {
            get {
                return ResourceManager.GetString("SizeMode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify manual に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizeMode4 {
            get {
                return ResourceManager.GetString("SizeMode4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Square trimming に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizeMode5 {
            get {
                return ResourceManager.GetString("SizeMode5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizeMode6 {
            get {
                return ResourceManager.GetString("SizeMode6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YES に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
